# Global LLM configuration
[llm]
api_type = 'ollama'
model = "gemma2:2b"
base_url = "http://localhost:11434/v1"
api_key = "ollama"
max_tokens = 4096
temperature = 0.0

[llm.vision]
api_type = 'ollama'
model = "gemma2:2b"
base_url = "http://localhost:11434/v1"
api_key = "ollama"
max_tokens = 4096
temperature = 0.0

[browser]
headless = true
disable_security = true 