# Streamlit Cloud secrets configuration
# Add your API keys here for Streamlit Cloud deployment

# OpenAI API Key (if using OpenAI models)
# OPENAI_API_KEY = "your-openai-api-key-here"

# Langfuse Configuration
# LANGFUSE_PUBLIC_KEY = "your-langfuse-public-key"
# LANGFUSE_SECRET_KEY = "your-langfuse-secret-key"
# LANGFUSE_HOST = "https://us.cloud.langfuse.com"

# Note: For local Ollama usage, no API keys are needed
# The app will automatically use gemma2:2b via Ollama
